name = "red-alert-backend"
main = "src/index.ts"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "ALERTS_KV"
id = "9c2055b0b0164a0eb2a0f8954a782346"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "feab25aac36840c2b2916c2f600a6c2b"

[triggers]
crons = ["* * * * *"]  # every minute

[durable_objects]
bindings = [
  { name = "ALERT_BROADCASTER", class_name = "AlertBroadcaster" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AlertBroadcaster"]
